l_polish:
 pm_military_priority:0 "Vojenská Priorita"
 pm_no_synthetic_dyes:0 "Žádné Syntetické Barviva"
 pm_rayon:0 "Rayon"
 pm_steamworks:0 "Parní Dílna"
 pmg_secondary_building_millet_farm:0 "Sekundární"
 pm_vacuum_evaporation:0 "Vakuová Evaporace"
 pm_ammonia-soda_process:0 "Proces Ammoniak-soda"
 pm_vineyards:0 "Vinice"
 pm_apple_orchards:0 "Jablečné Sady"
 pm_automatic_power_looms:0 "Automatické Tkalcovské Stavy"
 pm_craftsman_sewing:0 "Šití Řemeslníka"
 pm_electric_sewing_machines:0 "Elektrické Šicí Stroje"
 pm_nitrogen_fixation:0 "Proces Fixace Dusíku"
 pm_citrus_orchards:0 "Citrusové Sady"
 pm_no_secondary:0 "Udržovat Jednu Plodinu"
 pm_automobile_production:0 "Výroba Automobilů"
 pmg_automation:0 "Automatizace"
 pm_leaded_glass:0 "Sklo S Olovem"
 pm_mechanized_looms:0 "Mechanizované Tkalcovské Stavy"
 pmg_automation_building_tooling_workshops:0 "Automatizace"
 pmg_automation_building_furniture_manufacturies:0 "Automatizace"
 pmg_automation_building_motor_industry:0 "Automatizace"
 pmg_fertilizer_production:0 "Výroba Hnojiv"
 pmg_secondary_building_rice_farm:0 "Sekundární"
 pmg_secondary_building_maize_farm:0 "Sekundární"
 pm_fig_orchards:0 "Fíkové Sady"
 pmg_synthetic_dyes:0 "Syntetická Barviva"
 pm_primary:0 "Primární"
 pmg_secondary_building_wheat_farm:0 "Sekundární"
 pm_vineyards_building_maize_farm:0 "Vinice"
 pm_manual_glassblowing:0 "Ruční Sklenářství"
 pmg_automobile_production:0 "Výroba Automobilů"
 pm_civilian_priority:0 "Civilní Priorita"
 pmg_automation_building_food_industry:0 "Automatizace"
 pm_dyes_production:0 "Výroba Barviv"
 pm_artificial_fertilizers:0 "Umělá Hnojiva"
 pm_leblanc_process:0 "Leblancův Proces"
 pm_sewing_machines:0 "Šicí Stroje"
 pm_no_explosives_production:0 "Prioritizovat Výrobu Hnojiv"
 pm_no_artillery_production:0 "Prioritizovat Výrobu Malých Zbraní"
 pm_no_artificial_fibers:0 "Prioritizovat Výrobu Barviv"
 pm_traditional_looms:0 "Tradiční Tkalcovské Stavy"
 pmg_automation_building_paper_mills:0 "Automatizace"
 pm_no_artificial_fertilizers:0 "Žádná Umělá Hnojiva"
 pmg_secondary_building_rye_farm:0 "Sekundární"
 pm_artillery_production:0 "Výroba Děl"
 pm_mulberry_groves:0 "Morušové Háje"
 pmg_automation_building_textile_mills:0 "Automatizace"
 pm_silk_production:0 "Výroba Hedvábí"
 pm_fig_orchards_building_rice_farm:0 "Fíkové Sady"
 pm_potatoes:0 "Brambory"
 pm_brine_electrolysis:0 "Elektrolyza Solanky"
 pmg_automation_building_steel_mills:0 "Automatizace"
 pm_improved_fertilizer:0 "Zlepšená Hnojiva"
