l_polish:
 table_asset_3_theme: "Tabulka objekt (spodní levý roh)"
 SETTING_DAYNIGHT_CYCLE_TOOLTIP: "#T $SETTING_DAYNIGHT_CYCLE$#!\nPovoluje cyklus dne a noci pro pohyb slunce."
 SETTING_MAP_MODE_FADE_OUT:0 "Mód mapy Fade-out"
 table_asset_3_theme_desc: "Objekt zobrazený v dolním levém rohu tabulky vedle mapy při oddálení."
 SETTING_TOOLTIP_UNLOCK_TIME:0 "Zpoždění odemčení"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP:0 "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nNastaví zpoždění před tím, než jsou nápovědy uzamčeny, když je jiná nápověda již otevřená."
 SETTING_SHADER_QUALITY_TOOLTIP:1 "#T Kvalita shaderů\n#!Určuje kvalitu různých shaderů a efektů.\n\n#T Vysoká:#! Zlepšuje kvalitu některých shaderových efektů na úkor výkonu.\n\n#T Střední:#! Výchozí nastavení pro zamýšlený grafický zážitek.\n\n#T Nízká:#! Toto nastavení je určeno pro slabší stroje a není doporučeno kvůli ztrátě vizuální kvality. Mnohé shadery jsou zjednodušeny pro zvýšení grafického výkonu."
 papermap_theme: "Papírová mapa"
 SETTING_SOUNDTRACK:0 "Pozadí hudba"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_MOUSE_ANCHOR:0 "Akční uzamčení (Kotva myši)"
 SETTING_MAP_MODE_DELAY_TOOLTIP:0 "Zpoždění před přepnutím na nový Mód mapy, v sekundách"
 SETTINGS_CATEGORY_LANGUAGE:0 "Jazyk"
 SETTING_DAYNIGHT_SYSTEMTIME_TOOLTIP: "#T $SETTING_DAYNIGHT_SYSTEMTIME$#!\nSynchronizuje rychlost cyklu dne a noci a čas s místním časem počítače.\n\n#!Přepíše nastavení rychlosti simulace."
 OPTION_PORTRAIT_RENDER_SCALE_HIGH: "×2.0 - Vysoká"
 SETTINGS_CATEGORY_MFX:0 "Hudba"
 SETTING_DAYNIGHT_SPEED_TOOLTIP: "#T $SETTING_DAYNIGHT_SPEED$#!\nJak rychle bude čas cyklit mezi dnem a nocí.#"
 OPTION_PORTRAIT_RENDER_SCALE_NONE: "×1.0 - Žádná"
 SETTINGS_CATEGORY_SFX:1 "Zvukové efekty"
 table_asset_cloth_theme_desc: "Látka, na které leží mince."
 SETTING_TOOLTIP_MODE_NO_LOCK:0 "Žádné uzamčení"
 color_blind_mode_test:0 "Test"
 SETTING_OCCUPATION_STRIPES: "Pruhové vizuály povolání"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED:0 "Zamčené otevřené zpoždění"
 SETTING_TOOLTIP_LOCK_TIME:0 "Zpoždění uzamčení"
 SETTINGS_CATEGORY_GAME_PORTRAITS:0 "Portréty"
 SETTING_MUSIC_STINGERS:0 "Hudební výstřely"
 SETTING_SOUNDTRACK_TOOLTIP:0 "Obecná pozadí hudba"
 SETTING_MAP_MODE_FADE_OUT_TOOLTIP:0 "Čas pro aktuální Mód mapy, aby vybledl po zpoždění Módu mapy, když je třeba aplikovat nový Mód mapy, v sekundách"
 SETTING_SUNRISE_TIME: "Čas východu slunce"
 table_top_theme_desc: "Pokud se oddálíte co nejvíce na mapě, můžete vidět tuto tabulku nahoře a dole na obrazovce."
 building_sets_themes: "Sada budov"
 SETTINGS_CATEGORY_AUDIO_GENERAL:0 "Obecné"
 table_asset_4_theme: "Tabulka objekt (spodní pravý roh)"
 papermap_theme_desc: "Toto je mapa, kterou vidíte, když jste oddáleni."
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_WIDGET_ANCHOR:0 "Akční uzamčení"
 SETTING_DAYNIGHT_SET_TIME_TOOLTIP: "#T $SETTING_DAYNIGHT_SET_TIME$#!\nNastaví čas dne na určenou hodinu.\n\n#!Přepíše nastavení rychlosti simulace a synchronizuje místní čas."
 table_asset_4_theme_desc: "Objekt zobrazený v pravém dolním rohu tabulky vedle mapy při oddálení."
 table_asset_1_theme_desc: "Objekt zobrazený v levém horním rohu tabulky vedle mapy při oddálení."
 SETTING_MAP_MODE_FADE_IN:0 "Mód mapy Fade-in"
 SETTING_PORTRAIT_RENDER_SCALE_TOOLTIP: "#T $SETTING_PORTRAIT_RENDER_SCALE$#!\nZlepšuje úroveň detailů portrétu postavy zvětšením výsledků renderování, na úkor některého výkonu renderování."
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_WIDGET_ANCHOR:0 "Timming uzamčení"
 SETTINGS_CATEGORY_MAPMODES:0 "Módy mapy"
 SETTING_MAP_MODE_DELAY:0 "Zpoždění Módu mapy"
 SETTING_MAP_MODE_FADE_IN_TOOLTIP:0 "Čas pro nový Mód mapy, aby se vybledl po tom, co starý vybledl, v sekundách"
 ui_skin_theme_desc: "Tlačítka, rámy, okna, záhlaví atd. ve hře."
 SETTING_VALUE_HOUR_FULL: "$VALUE|0$:00"
 SETTING_PAUSE_ON_EVENT_MESSAGE_SETTINGS: "$SETTING_PAUSE_ON_EVENT$ (pouze pro jednoho hráče)"
 SETTINGS_CATEGORY_SAVE_GAMES:0 "Uložit Hry"
 SETTING_TOOLTIP_DELAY_TOOLTIP:1 "#T $SETTING_TOOLTIP_DELAY$#!\nNastaví zpoždění před tím, než se nápověda zobrazí, když je kurzor nad prvkem s nápovědou."
 SETTING_BUILDINGS_CUTOFF:1 "Odstranit vzdálené budovy"
 table_asset_cloth_theme: "Tabulka ubrus"
 SETTING_SUNRISE_SET_TIME_HOUR: "Ruční čas hodiny"
 SETTING_DAYNIGHT_CYCLE: "Povolit cyklus dne a noci"
 SETTINGS_CATEGORY_GAME_NOTIFICATIONS: "Oznámení"
 SETTING_PAUSE_ON_EVENT_TOOLTIP: "#T $SETTING_PAUSE_ON_EVENT$#!\nZastaví hru a zobrazí popup, když dojde k události."
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS:0 "Pokročilé"
 SETTINGS_CATEGORY_TOOLTIPS:0 "Nastavení nápovědy"
 SETTING_SUNRISE_SET_TIME_HOUR_TOOLTIP: "#T $SETTING_SUNRISE_SET_TIME_HOUR$#!\nZamkne čas na tuto hodinu.\n\n#!Používá se pouze při povoleném ručním čase#"
 OPTION_SAVE_FILE_ZIP_TEXT_ALL:0 "Zkomprimovaný text"
 SETTING_MAP_TOOLTIP_DELAY:0 "Zpoždění nápovědy mapy"
 SETTING_DAYNIGHT_SPEED: "Rychlost simulace"
 SETTING_TOOLTIP_MODE:0 "Režim nápovědy"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY:0 "Tendence myši"
 SETTING_SUN_DURATION: "Hodiny slunce"
 SETTING_AMBIENT:0 "Ambience"
 SETTING_MAP_TOOLTIP_DELAY_TOOLTIP:0 "#T $SETTING_MAP_TOOLTIP_DELAY$#!\nNastaví zpoždění před zobrazením nápovědy mapy."
 table_top_theme: "Hlava stolu"
 table_asset_2_theme: "Tabulka objekt (pravý horní roh)"
 SETTING_PAUSE_ON_EVENT: "Pozastavit a popup na události"
 SETTING_VALUE_HOURS: "$VALUE|0$ Hodiny"
 SETTING_TOOLTIP_MODE_TOOLTIP:2 "#T $SETTING_TOOLTIP_MODE$#!\nVyberte, jak by se měly nápovědy uzamykat:\n   #b Tendence myši#! - Uzamkne ji, pokud posunete myš směrem k nápovědě.\n   #b Timming uzamčení#! - Uzamkne ji po nastaveném čase.\n   #b Akční uzamčení#! - Uzamkne ji prostředním tlačítkem myši.\n   #b Timming nebo akční uzamčení#! - Může použít buď Timming uzamčení nebo Akční uzamčení."
 SETTING_SHOW_NOTIFICATION_FEED_NEXT_TO_OUTLINER: "Oznámení vlevo od rozložení"
 SETTING_MUSIC_STINGERS_TOOLTIP:0 "Krátké hudební fráze pro zlepšení herního zážitku"
 SETTING_TOOLTIP_DELAY:0 "Zobrazit zpoždění"
 SETTING_SAVE_FILE_FORMAT_TOOLTIP:0 "Tato volba je přepsána v režimu Ironman, Cloud a Debug"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP:0 "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nNastaví zpoždění před odemčením nápověd."
 SETTING_MUSIC_TOOLTIP:0 "#T Hlasitost hudby\n#!Nastaví hlasitost hudby."
 SETTING_SAVE_FILE_FORMAT:0 "Výchozí formát uložení"
 SETTING_SHOW_NUDITY:0 "Zobrazit nahotu"
 SETTING_SUNRISE_TIME_TOOLTIP: "#T $SETTING_SUNRISE_TIME$#!\nHodina, kdy slunce vyjde.\n\n#!Používá se pouze při synchronizaci s místním časem. #!"
 table_asset_1_theme: "Tabulka objekt (levý horní roh)"
 OPTION_PORTRAIT_RENDER_SCALE_MEDIUM: "×1.5 - Střední"
 OPTION_SAVE_FILE_TEXT:0 "Text"
 SETTING_SHOW_NOTIFICATION_FEED_NEXT_TO_OUTLINER_TOOLTIP: "#t $SETTING_SHOW_NOTIFICATION_FEED_NEXT_TO_OUTLINER$#!\nUmístěte Oznámení do levé části rozložení"
 SETTING_MUSIC:0 "Hudba"
 SETTINGS_CATEGORY_OUTLINER:0 "Rozložení"
 table_asset_2_theme_desc: "Objekt zobrazený v pravém horním rohu tabulky vedle mapy při oddálení."
 SETTING_AUTOSAVE_TO_CLOUD:0 "Automatické uložení do cloudu"
 ui_skin_theme: "Uživatelské rozhraní"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_OR_ACTION_WIDGET_ANCHOR: "Timming nebo akční uzamčení"
 SETTING_SHADER_QUALITY:0 "Kvalita shaderů"
 SETTING_DAYNIGHT_SET_TIME: "Povolit ruční čas"
 SETTING_DAYNIGHT_SYSTEMTIME: "Povolit synchronizaci místního času"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP:0 "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nNastaví zpoždění před uzamčením nápověd."
 OPTION_SAVE_FILE_ZIP_BINARY_ALL:0 "Zkomprimovaný binární"
 SETTING_SHOW_NUDITY_TOOLTIP:0 "#T $SETTING_SHOW_NUDITY$#!\nNastaví, zda mohou být postavy zobrazeny nahé."
 SETTING_BUILDINGS_CUTOFF_TOOLTIP:1 "#T $SETTING_BUILDINGS_CUTOFF$#!\nZobrazuje méně budov na mapě, čím dál jsou od kamery.\n\nPovolení může zvýšit výkon."
 SETTING_SUN_DURATION_TOOLTIP: "#T $SETTING_SUN_DURATION$#!\nPočet hodin slunce za den."
 SETTINGS_CATEGORY_DAYNIGHT_CYCLE: "Cyklus dne a noci"
 SETTING_OCCUPATION_STRIPES_TOOLTIP: "#T $SETTING_OCCUPATION_STRIPES$#!\nPovolit barevné pruhy jako vizuály povolání na mapě namísto textur vlajek zemí."
 SETTINGS_CATEGORY_MAP_CONTROLS:0 "Ovládání mapy"
 SETTING_AMBIENT_TOOLTIP:0 "#T Hlasitost ambientu\n#!Nastaví hlasitost prostředí."
 SETTING_PORTRAIT_RENDER_SCALE: "Měřítko renderování portrétu"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_MOUSE_ANCHOR:0 "Timming uzamčení (Kotva myši)"
