l_polish:
 CAMERA_FPS: "První osoba"
 CAMERA_TABLETOP: "Pohled shora"
 CAMERA_WASD: "Styl WASD"
 GAMEPAD: "Gamepad"
 MOUSE_AND_KEYBOARD: "Myš a klávesnice"
 NO_AUTOSAVE: "Bez automatického ukládání"
 OPTION_ANTI_ALIASING_DISABLED: "Vypnuto"
 OPTION_ANTI_ALIASING_FXAA: "FXAA"
 OPTION_CAP_120: "120"
 OPTION_CAP_144: "144"
 OPTION_CAP_165: "165"
 OPTION_CAP_30: "30"
 OPTION_CAP_60: "60"
 OPTION_CAP_90: "90"
 OPTION_CUSTOM: "Vlastní"
 OPTION_DEFAULT: "Výchozí"
 OPTION_DISABLED: "Vypnuto"
 OPTION_FULLSCREEN: "Celá obrazovka"
 OPTION_FULLSCREEN_TOOLTIP: "#T $OPTION_FULLSCREEN$\n#!Zobrazí hru na celé obrazovce. Rozlišení ovlivňuje ostrost obrazu."
 OPTION_HIGH: "Vysoké"
 OPTION_LOW: "Nízké"
 OPTION_MEDIUM: "Střední"
 OPTION_OFF: "Vypnuto"
 OPTION_ULTRA: "Ultra vysoké"
 OPTION_UPSCALE_DLSS: "NVIDIA DLSS"
 OPTION_UPSCALE_FSR2: "AMD FidelityFX Super Resolution 2"
 OPTION_UPSCALE_QUALITY_BALANCED: "Vyvážené"
 OPTION_UPSCALE_QUALITY_PERFORMANCE: "Výkon"
 OPTION_UPSCALE_QUALITY_QUALITY: "Kvalita"
 OPTION_UPSCALE_QUALITY_ULTRA_PERFORMANCE: "Ultra výkon"
 OPTION_UPSCALE_QUALITY_ULTRA_QUALITY: "Ultra kvalita"
 OPTION_UPSCALE_XESS: "Intel® XeSS"
 OPTION_VERY_HIGH: "Velmi vysoké"
 OPTION_WINDOWED: "Okno"
 OPTION_WINDOWED_TOOLTIP: "#T $OPTION_WINDOWED$\n#!Zobrazí hru v okně. Rozlišení mění velikost okna."
 SETTINGS_CATEGORY_ACCESSIBILITY: "Přístupnost"
 SETTINGS_CATEGORY_GAME: "Hra"
 SETTINGS_CATEGORY_UI: "Uživatelské rozhraní"
 SETTINGS_FILE_TRANSFER_SPEED: "Rychlost přenosu souborů"
 SETTINGS_FILE_TRANSFER_SPEED_TOOLTIP: "#T $SETTINGS_FILE_TRANSFER_SPEED$#!\nNastavuje maximální rychlost pro přenos uložených her v multiplayerové lobby.\n\nNižší nastavení může zlepšit stabilitu sítě při připojování do multiplayerových her, ale má negativní vliv na dobu načítání.\n\nHostitel multiplayeru určuje maximální rychlost.\n"
 SETTING_ACCOUNT_EMAIL_TOOLTIP: "E-mail vašeho Paradox účtu"
 SETTING_ANIMATION_SPEED: "Rychlost animace"
 SETTING_ANISOTROPIC_FILTERING: "Filtrace textur"
 SETTING_ANISOTROPIC_FILTERING_DISABLED: "Vypnuto"
 SETTING_ANISOTROPIC_FILTERING_TOOLTIP: "#T $SETTING_ANISOTROPIC_FILTERING$\n#!Použití anisotropního filtrování zlepšuje kvalitu textur na površích.\n\nNižší nastavení může zvýšit výkon."
 SETTING_ANTI_ALIASING: "Vyhlazování hran"
 SETTING_ANTI_ALIASING_TOOLTIP: "#T $SETTING_ANTI_ALIASING$\n#!Použití vyhlazování hran zjemňuje okraje objektů.\n\nFXAA je doporučeno."
 SETTING_AUDIO_DEBUG_LOG_LEVEL: "Úroveň ladicího logu"
 SETTING_AUDIO_DEVICE_PROFILE: "Zvukový profil"
 SETTING_AUDIO_DEVICE_PROFILE_TOOLTIP: "#T $SETTING_AUDIO_DEVICE_PROFILE$\n#!Vyberte zvukový profil, který odpovídá vašemu nastavení."
 SETTING_AUDIO_OPTION_HEADPHONES: "Sluchátka"
 SETTING_AUDIO_OPTION_HEADPHONES_TOOLTIP: "#T $SETTING_AUDIO_OPTION_HEADPHONES$\n#!Mix přizpůsobený pro $SETTING_AUDIO_OPTION_HEADPHONES$."
 SETTING_AUDIO_OPTION_NIGHTMODE: "Noční režim"
 SETTING_AUDIO_OPTION_NIGHTMODE_TOOLTIP: "#T $SETTING_AUDIO_OPTION_NIGHTMODE$\n#!Zjemňuje zvuk pro noční hraní, tlumí vyšší tóny a komprimuje dynamický rozsah."
 SETTING_AUDIO_OPTION_SPEAKERS: "Reproduktory"
 SETTING_AUDIO_OPTION_SPEAKERS_TOOLTIP: "#T $SETTING_AUDIO_OPTION_SPEAKERS$\n#!Výchozí mix pro $SETTING_AUDIO_OPTION_SPEAKERS$."
 SETTING_AUDIO_OPTION_TV: "Televize"
 SETTING_AUDIO_OPTION_TV_TOOLTIP: "#T $SETTING_AUDIO_OPTION_TV$\n#!Mix pro $SETTING_AUDIO_OPTION_TV$ a reproduktory monitoru."
 SETTING_AUTOSAVE: "Interval automatického ukládání"
 SETTING_AUTOSAVE_TOOLTIP: "#T $SETTING_AUTOSAVE$\n#!Nastavuje, jak často se hra bude automaticky ukládat."
 SETTING_AUTOSAVE_TO_CLOUD_TOOLTIP: "Určuje, zda se automatická uložení ukládají do cloudu."
 SETTING_Ambient: "Okolní zvuky"
 SETTING_Ambient_TOOLTIP: "#T Hlasitost okolních zvuků\n#!Nastavuje hlasitost zvuků prostředí."
 SETTING_BLOOM_QUALITY: "Bloom"
 SETTING_BLOOM_QUALITY_TOOLTIP: "#T $SETTING_BLOOM_QUALITY$\n#!Povolí efekt rozjasnění, kde velmi jasná světla rozlévají světlo do dalších částí obrazu.\n\nNižší nastavení může zvýšit výkon."
 SETTING_CAMERA_FACE_NORTH_TOOLTIP: "Určuje, zda bude kamera vždy směřovat na sever."
 SETTING_CAMERA_ROTATION_SPEED: "Rychlost otáčení kamery"
 SETTING_CAMERA_ROTATION_SPEED_TOOLTIP: "#T $SETTING_CAMERA_ROTATION_SPEED$#!\nRychlost otáčení kamery."
 SETTING_CAMERA_SPEED: "Rychlost kamery"
 SETTING_CAMERA_STRATEGY: "Typ kamery"
 SETTING_CAMERA_TILT: "Náklon kamery"
 SETTING_CENTERED_ZOOM_IN: "Centrovaný zoom"
 SETTING_CODE_EDITOR_OPEN_FILE_FORMAT: "Příkaz pro otevření editoru kódu"
 SETTING_COLOR_BLIND_MODE: "Režim pro barvoslepé"
 SETTING_COLOR_BLIND_MODE_TOOLTIP: "#T $SETTING_COLOR_BLIND_MODE$\n#!Mění barvy použité ve hře na sadu, která je snadněji rozlišitelná pro různé typy barvosleposti."
 SETTING_CONSOLE_AUTOCOMPLETE_MODE: "Režim automatického doplňování konzole"
 SETTING_CONSOLE_AUTOCOMPLETE_MODE_FULL_EXPAND: "Plné rozbalení, iterace s tabulátorem"
 SETTING_CONSOLE_AUTOCOMPLETE_MODE_PARTIAL_EXPAND: "Částečné rozbalení do rozdílu"
 SETTING_DISPLAY: "Monitor"
 SETTING_DISPLAY_MODE: "Režim zobrazení"
 SETTING_DISPLAY_MODE_TOOLTIP: "#T $SETTING_DISPLAY_MODE$\n#!Určuje, jak bude hra zobrazena na obrazovce."
 SETTING_DISPLAY_TOOLTIP: "#T $SETTING_DISPLAY$\n#!Pokud má váš počítač více monitorů, vyberte, který z nich bude hra používat."
 SETTING_DOF_TOOLTIP: "#T $SETTING_DOF$\n#!Zapíná hloubku ostrosti k simulaci objektivu kamery, rozmazává neostré části obrazu.\n\nVypnutí může zvýšit výkon."
 SETTING_EDITOR: "Editor"
 SETTING_EDITOR_OPEN_FILE_FORMAT: "Příkaz pro otevření editoru"
 SETTING_EDITOR_POSTFIX: "Postfix editoru"
 SETTING_Effects: "Efekty"
 SETTING_FILL_IN_IMPASSABLE_TERRAIN_TOOLTIP: "Určuje, zda je neprostupný terén zahrnut do hranic národa na mapě."
 SETTING_FRAMERATE_CAP: "Maximální FPS"
 SETTING_FRAMERATE_CAP_TOOLTIP: "#T $SETTING_FRAMERATE_CAP$#!\nMaximální FPS, které hra vykreslí.\n\nNižší nastavení může snížit spotřebu energie."
 SETTING_GRACEFUL_EXIT: "Elegantní ukončení"
 SETTING_GRAPHICS_DEVICE: "Grafická karta"
 SETTING_GRAPHICS_DEVICE_TOOLTIP: "#T $SETTING_GRAPHICS_DEVICE$\n#!Vyberte grafickou kartu, kterou hra použije.\n\nPoužití integrované grafické karty nebo softwarového renderování může snížit výkon."
 SETTING_GUI_SCALING: "Škálování rozhraní"
 SETTING_GUI_SCALING_TOOLTIP: "#T $SETTING_GUI_SCALING$\n#!Nastavuje měřítko celého uživatelského rozhraní. Užitečné pro vyšší rozlišení obrazovky.\n\n#X Příliš vysoké nastavení způsobí, že se rozhraní nevejde na obrazovku!#!"
 SETTING_INPUT_DEVICE: "Vstupní zařízení"
 SETTING_LANGUAGE: "Jazyk"
 SETTING_LANGUAGE_TOOLTIP: "#T $SETTING_LANGUAGE$#!\nUrčuje jazyk uživatelského rozhraní."
 SETTING_LENS_FLARE_TOOLTIP: "#T $SETTING_LENS_FLARE$\n#!Zapíná efekt odlesků objektivu v místech s vysokým jasem. Bloom musí být zapnut pro zobrazení efektu. \n\nVypnutí může zvýšit výkon."
 SETTING_LOG_VIEWER_OPEN_FILE_FORMAT: "Příkaz pro zobrazení logu"
 SETTING_MAPOBJECT_QUALITY_TOOLTIP: "#T $SETTING_MAPOBJECT_QUALITY$#!\nUrčuje nejvyšší úroveň kvality objektů na mapě (například budovy).\n\nNižší nastavení může zvýšit výkon."
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES: "Automatické ukládání editoru mapy (minuty)"
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES_TOOLTIP: "Interval automatického ukládání editoru mapy (minuty)"
 SETTING_MAP_SSAO_TOOLTIP: "#T $SETTING_MAP_SSAO$\n#!Určuje, zda se na mapu použije ambientní okluze obrazovky.\n\nVypnutí může zvýšit výkon."
 SETTING_MESH_LOD_BIAS: "Kvalita LOD"
 SETTING_MESH_LOD_BIAS_TOOLTIP: "#T $SETTING_MESH_LOD_BIAS$#!\nUrčuje kvalitu LOD (úrovní detailů) u objektů na mapě jako jsou modely jednotek.\n\nNižší nastavení může zvýšit výkon."
 SETTING_MESH_LOD_FADE: "Plynulé přepínání LOD"
 SETTING_MESH_LOD_FADE_TOOLTIP: "#T $SETTING_MESH_LOD_FADE$\n#!Pokud je zapnuto, 3D modely plynule přecházejí mezi různými úrovněmi detailů při přibližování a oddalování.\n\nVypnutí může zvýšit výkon."
 SETTING_MOUSE_CURSOR_ZOOM_MODE: "Chování zoomu"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_IGNORE_CURSOR: "Ignorovat kurzor"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_RELATIVE_CURSOR: "Relativní kurzor"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_TOOLTIP: "#T $SETTING_MOUSE_CURSOR_ZOOM_MODE$#!\nJak se kamera chová vzhledem k myši při zoomování."
 SETTING_MOUSE_CURSOR_ZOOM_MODE_ZOOM_IN_TO_CURSOR: "Zoom na kurzor"
 SETTING_MULTISAMPLING_DISABLED: "Zakázáno"
 SETTING_MULTI_SAMPLING: "Vyhlazování hran (MSAA)"
 SETTING_MULTI_SAMPLING_TOOLTIP: "#T $SETTING_MULTI_SAMPLING$\n#!Použití multi-samplingu (MSAA) vyhlazuje okraje objektů.\n\nNižší nastavení může zvýšit výkon."
 SETTING_MUSIC_DENSITY: "Hustota hudby"
 SETTING_MUSIC_DENSITY_TOOLTIP: "Ovládá poměr mezi plnými skladbami, tichem a atmosférickou hudbou.\n\nIntenzivní = Hraje se většinou skladba za skladbou, podobně jako na 'rádiu'.\nVyvážené = Perfektní rovnováha mezi skladbami, tichem a atmosférou\nUvolněné = Převážně klidné skladby pro lepší atmosféru a menší opakování po několika hodinách hraní"
 SETTING_Master: "Hlavní"
 SETTING_Master_TOOLTIP: "#T Hlavní hlasitost\n#!Nastavuje hlasitost všech zvuků ve hře."
 SETTING_Music: "Hudba"
 SETTING_Music_TOOLTIP: "#T Hlasitost hudby\n#!Nastavuje hlasitost hudby."
 SETTING_NODE_EDITOR_DRAG_PAN_MODE: "Režim tažení v editoru uzlů"
 SETTING_PORTRAIT_MULTISAMPLING_DISABLED: "Zakázáno"
 SETTING_PORTRAIT_MULTI_SAMPLING: "Portrét MultiSampling"
 SETTING_PORTRAIT_MULTI_SAMPLING_TOOLTIP: "#T $SETTING_PORTRAIT_MULTI_SAMPLING$\n#!Použití multi-samplingu pro Alpha-To-Coverage ke zjemnění míchání vlasů.\n\nNižší nastavení zvyšuje výkon."
 SETTING_PROVINCE_NAMES_TOOLTIP: "Určuje, jak se na mapě zobrazují názvy měst a provincií."
 SETTING_QUALITY: "Předvolba kvality"
 SETTING_QUALITY_TOOLTIP: "#T $SETTING_QUALITY$\n#!Vyberte přednastavení pokročilých grafických možností níže.\n\nNižší předvolby mohou zvýšit výkon."
 SETTING_REFRACTION_QUALITY_TOOLTIP: "#T $SETTING_REFRACTION_QUALITY$#!\nOvládá kvalitu lomu světla na vodě, pokud je povolen.\n\nNižší nastavení může zvýšit výkon."
 SETTING_REFRACTION_TOOLTIP: "Určuje, zda se na vodě zobrazí lom světla."
 SETTING_RENDERER: "Renderer"
 SETTING_RENDERER_TOOLTIP: "Určuje, který renderer je používán."
 SETTING_RENDER_SCALE: "Měřítko renderování"
 SETTING_RENDER_SCALE_FORMAT: "$VALUE|%0$"
 SETTING_RENDER_SCALE_TOOLTIP: "#T $SETTING_RENDER_SCALE$#!\nMěřítko renderovacího rozlišení hry vzhledem k hlavnímu rozlišení, s výjimkou uživatelského rozhraní.\n\nNižší nastavení může zvýšit výkon, ale sníží kvalitu, zatímco nastavení nad 100 % může zvýšit kvalitu, ale pravděpodobně sníží výkon."
 SETTING_RESOLUTION: "Rozlišení"
 SETTING_RESOLUTION_TOOLTIP: "#T $SETTING_RESOLUTION$\n#!Nastavuje kvalitu obrazu ve hře.\n\nNižší rozlišení může zvýšit výkon.\n\n#X Rozlišení s nepodporovaným poměrem stran může způsobit, že se rozhraní nevejde na obrazovku#!"
 SETTING_SCREEN_EDGE_SCROLL_DISABLED: "Zakázáno"
 SETTING_SCREEN_EDGE_SCROLL_MODE: "Posun myší"
 SETTING_SCREEN_EDGE_SCROLL_MODE_8_DIRECTIONS: "8 směrů"
 SETTING_SCREEN_EDGE_SCROLL_MODE_FREE: "Volný"
 SETTING_SCREEN_EDGE_SCROLL_MODE_TOOLTIP: "#T $SETTING_SCREEN_EDGE_SCROLL_MODE$#!\nJak se kamera chová při posunu myší."
 SETTING_SCROLL_SPEED: "Rychlost posunu"
 SETTING_SCROLL_SPEED_TOOLTIP: "#T $SETTING_SCROLL_SPEED$#!\nNastavuje rychlost posunu mapy při použití klávesnice nebo myši."
 SETTING_SECONDARY_LENS_FLARE_TOOLTIP: "#T $SETTING_SECONDARY_LENS_FLARE$\n#!Zapíná sekundární efekt odlesků objektivu v jasných oblastech. Bloom musí být zapnut pro zobrazení efektu. \n\nVypnutí může zvýšit výkon."
 SETTING_SFX: "Zvukové efekty"
 SETTING_SFX_TOOLTIP: "#T Hlasitost efektů\n#!Nastavuje hlasitost zvukových efektů, například boje."
 SETTING_SHADOW_MAP_RESOLUTION: "Kvalita stínů"
 SETTING_SHADOW_MAP_RESOLUTION_TOOLTIP: "#T $SETTING_SHADOW_MAP_RESOLUTION$\n#!Určuje rozlišení stínových map, pokud jsou stíny povoleny.\n\nNižší nastavení může zvýšit výkon."
 SETTING_TERRAIN_SMOOTHING: "Vyhlazování terénu"
 SETTING_TEXTURE_QUALITY: "Kvalita textur"
 SETTING_TEXTURE_QUALITY_TOOLTIP: "#T $SETTING_TEXTURE_QUALITY$\n#!Ovládá rozlišení načítaných textur.\n\nNižší nastavení může zvýšit výkon."
 SETTING_TEXTURE_STREAMING: "Streamování textur"
 SETTING_TEXTURE_STREAMING_CACHE: "Velikost mezipaměti streamování textur"
 SETTING_TEXTURE_STREAMING_TOOLTIP: "#T $SETTING_TEXTURE_STREAMING$#!\nTextury se načítají podle potřeby.\n\nSnižuje využití paměti GPU za cenu větší zátěže CPU. Může zlepšit výkon na GPU s malou pamětí."
 SETTING_TOOLS_GUI_SCALING: "Škálování rozhraní nástrojů"
 SETTING_TOOLS_GUI_SCALING_TOOLTIP: "#T $SETTING_TOOLS_GUI_SCALING$\n#!Nastavuje měřítko rozhraní nástrojů. Užitečné pro vyšší rozlišení obrazovky.\n\n#X Příliš vysoké nastavení způsobí, že se rozhraní nevejde na obrazovku!#!"
 SETTING_UI: "Uživatelské rozhraní"
 SETTING_UI_TOOLTIP: "#T Hlasitost rozhraní\n#!Nastavuje hlasitost uživatelského rozhraní."
 SETTING_UPSCALE: "Metoda upscalingu"
 SETTING_UPSCALE_QUALITY: "Kvalita upscalingu"
 SETTING_UPSCALE_QUALITY_TOOLTIP: "#T $SETTING_UPSCALE_QUALITY$#!\nNastaví upscaling od nejvyšší kvality po nejvyšší výkon."
 SETTING_UPSCALE_TOOLTIP: "#T $SETTING_UPSCALE$#!\nMetody upscalingu umožňují dosažení vyššího rozlišení pomocí algoritmického upsampling. To může zlepšit výkon, ale může vést k vizuálním artefaktům nebo jinému neočekávanému chování.\n\nDostupné metody upscalingu mohou záviset na vaší grafické kartě."
 SETTING_VALUE_MB: "$VALUE$ MB"
 SETTING_VALUE_MINUTES: "$VALUE$ minut"
 SETTING_VALUE_NONE: "$VALUE$"
 SETTING_VALUE_PERCENTAGE: "$VALUE|%0$"
 SETTING_VALUE_SECONDS: "$VALUE$ sekund"
 SETTING_VALUE_TOTAL_PERCENTAGE: "$VALUE|%/0$"
 SETTING_VO: "Dabing"
 SETTING_VO_TOOLTIP: "#T Hlasitost dabingu\n#!Nastavuje hlasitost dabingu ve hře."
 SETTING_VSYNC: "VSync"
 SETTING_VSYNC_TOOLTIP: "#T $SETTING_VSYNC$\n#!Synchronizuje snímkovou frekvenci hry s monitorem, což snižuje trhání obrazu.\n\nVypnutí může zvýšit výkon."
 SETTING_ZOOM_SPEED: "Rychlost zoomu"
 SETTING_ZOOM_SPEED_TOOLTIP: "#T $SETTING_ZOOM_SPEED$#!\nRychlost přibližování kamery."
