l_polish:
  SETTING_VALUE_NONE: "$VALUE$"
  SETTING_VALUE_TOTAL_PERCENTAGE: "$VALUE|%/0$"
  SETTING_VALUE_PERCENTAGE: "$VALUE|%0$"
  SETTING_VALUE_SECONDS: "$VALUE$ sekund"
  SETTING_VALUE_MINUTES: "$VALUE$ minut"
  # Grafika
  SETTING_RENDERER: "Renderer"
  SETTING_RENDERER_TOOLTIP: "Určuje, který renderer je používán."
  SETTING_VSYNC: "VSync"
  SETTING_VSYNC_TOOLTIP: "#T $SETTING_VSYNC$\n#!Synchronizuje snímkovou frekvenci hry s monitorem, což snižuje trhání obrazu.\n\nVypnutí může zvýšit výkon."
  SETTING_PORTRAIT_MULTI_SAMPLING: "Portrét MultiSampling"
  SETTING_PORTRAIT_MULTI_SAMPLING_TOOLTIP: "#T $SETTING_PORTRAIT_MULTI_SAMPLING$\n#!Použití multi-samplingu pro Alpha-To-Coverage ke zjemnění míchání vlasů.\n\nNižší nastavení zvyšuje výkon."
  SETTING_MULTI_SAMPLING: "Vyhlazování hran (MSAA)"
  SETTING_MULTI_SAMPLING_TOOLTIP: "#T $SETTING_MULTI_SAMPLING$\n#!Použití multi-samplingu (MSAA) vyhlazuje okraje objektů.\n\nNižší nastavení může zvýšit výkon."
  SETTING_ANTI_ALIASING: "Vyhlazování hran"
  SETTING_ANTI_ALIASING_TOOLTIP: "#T $SETTING_ANTI_ALIASING$\n#!Použití vyhlazování hran zjemňuje okraje objektů.\n\nFXAA je doporučeno."
  OPTION_ANTI_ALIASING_DISABLED: "Vypnuto"
  OPTION_ANTI_ALIASING_FXAA: "FXAA"
  SETTING_UPSCALE: "Metoda upscalingu"
  SETTING_UPSCALE_TOOLTIP: "#T $SETTING_UPSCALE$#!\nMetody upscalingu umožňují dosažení vyššího rozlišení pomocí algoritmického upsampling. To může zlepšit výkon, ale může vést k vizuálním artefaktům nebo jinému neočekávanému chování.\n\nDostupné metody upscalingu mohou záviset na vaší grafické kartě."
  OPTION_UPSCALE_FSR2: "AMD FidelityFX Super Resolution 2"
  OPTION_UPSCALE_DLSS: "NVIDIA DLSS"
  OPTION_UPSCALE_XESS: "Intel® XeSS"
  SETTING_UPSCALE_QUALITY: "Kvalita upscalingu"
  SETTING_UPSCALE_QUALITY_TOOLTIP: "#T $SETTING_UPSCALE_QUALITY$#!\nNastaví upscaling od nejvyšší kvality po nejvyšší výkon."
  OPTION_UPSCALE_QUALITY_ULTRA_QUALITY: "Ultra kvalita"
  OPTION_UPSCALE_QUALITY_QUALITY: "Kvalita"
  OPTION_UPSCALE_QUALITY_BALANCED: "Vyvážené"
  OPTION_UPSCALE_QUALITY_PERFORMANCE: "Výkon"
  OPTION_UPSCALE_QUALITY_ULTRA_PERFORMANCE: "Ultra výkon"
  SETTING_ANISOTROPIC_FILTERING: "Filtrace textur"
  SETTING_ANISOTROPIC_FILTERING_TOOLTIP: "#T $SETTING_ANISOTROPIC_FILTERING$\n#!Použití anisotropního filtrování zlepšuje kvalitu textur na površích.\n\nNižší nastavení může zvýšit výkon."
  SETTING_FULLSCREEN_RESOLUTION: "Rozlišení"
  SETTING_FULLSCREEN_RESOLUTION_TOOLTIP: "#T $SETTING_FULLSCREEN_RESOLUTION$\n#!Nastaví kvalitu obrazu hry.\n\nNižší rozlišení může zvýšit výkon.\n\n#X Rozlišení s nepodporovaným poměrem stran může způsobit, že rozhraní bude mimo obrazovku!#!"
  SETTING_WINDOWED_RESOLUTION: "Rozlišení v okně"
  SETTING_WINDOWED_RESOLUTION_TOOLTIP: "#T $SETTING_WINDOWED_RESOLUTION$\n#!Nastaví rozlišení hry v okně.\n\nMusí být ve formátu #b ČÍSLO#!x#b ČÍSLO#!.\n\n#X Rozlišení s nepodporovaným poměrem stran může způsobit, že rozhraní bude mimo obrazovku!#!"
  SETTING_RENDER_SCALE: "Měřítko renderování"
  SETTING_RENDER_SCALE_TOOLTIP: "#T $SETTING_RENDER_SCALE$#!\nMěřítko renderovacího rozlišení hry vzhledem k hlavnímu rozlišení, s výjimkou uživatelského rozhraní.\n\nNižší nastavení může zvýšit výkon, ale sníží kvalitu, zatímco nastavení nad 100 % může zvýšit kvalitu, ale pravděpodobně sníží výkon."
  SETTING_RENDER_SCALE_FORMAT: "$VALUE|%0$"
  SETTING_DISPLAY: "Monitor"
  SETTING_DISPLAY_TOOLTIP: "#T $SETTING_DISPLAY$\n#!Pokud má váš počítač více monitorů, vyberte, který z nich bude hra používat."
  SETTING_GRAPHICS_DEVICE: "Grafická karta"
  SETTING_GRAPHICS_DEVICE_TOOLTIP: "#T $SETTING_GRAPHICS_DEVICE$\n#!Vyberte grafickou kartu, kterou hra použije.\n\nPoužití integrované grafické karty nebo softwarového renderování může snížit výkon."
  SETTING_SHADOW_MAP_RESOLUTION: "Kvalita stínů"
  SETTING_SHADOW_MAP_RESOLUTION_TOOLTIP: "#T $SETTING_SHADOW_MAP_RESOLUTION$\n#!Určuje rozlišení stínových map, pokud jsou stíny povoleny.\n\nNižší nastavení může zvýšit výkon."
  SETTING_DISPLAY_MODE: "Režim zobrazení"
  SETTING_DISPLAY_MODE_TOOLTIP: "#T $SETTING_DISPLAY_MODE$\n#!Určuje, jak bude hra zobrazena na obrazovce."
  SETTING_BLOOM_QUALITY: "Bloom"
  SETTING_MESH_LOD_BIAS: "Kvalita LOD"
  SETTING_MESH_LOD_FADE: "Plynulé přepínání LOD"
  SETTING_TERRAIN_SMOOTHING: "Vyhlazování terénu"
  OPTION_FULLSCREEN: "Celá obrazovka"
  OPTION_FULLSCREEN_TOOLTIP: "#T $OPTION_FULLSCREEN$\n#!Zobrazí hru na celé obrazovce. Rozlišení ovlivňuje ostrost obrazu."
  OPTION_WINDOWED: "Okno"
  OPTION_WINDOWED_TOOLTIP: "#T $OPTION_WINDOWED$\n#!Zobrazí hru v okně. Rozlišení mění velikost okna."
  OPTION_DISABLED: "Vypnuto"
  OPTION_OFF: "Vypnuto"
  OPTION_LOW: "Nízké"
  OPTION_MEDIUM: "Střední"
  OPTION_HIGH: "Vysoké"
  OPTION_ULTRA: "Ultra"
  OPTION_CUSTOM: "Vlastní"
  OPTION_DEFAULT: "Výchozí"
  SETTINGS_CATEGORY_UI: "Uživatelské rozhraní"
  SETTINGS_CATEGORY_GAME: "Hra"
  SETTING_TEXTURE_QUALITY: "Kvalita textur"
  SETTING_TEXTURE_QUALITY_TOOLTIP: "#T $SETTING_TEXTURE_QUALITY$\n#!Ovládá rozlišení načítaných textur.\n\nNižší nastavení může zvýšit výkon."
  SETTING_QUALITY: "Předvolba kvality"
  SETTING_SFX: "Zvukové efekty"
  SETTING_UI: "Uživatelské rozhraní"
  SETTING_QUALITY_TOOLTIP: "#T $SETTING_QUALITY$\n#!Vyberte přednastavení pokročilých grafických možností níže.\n\nNižší předvolby mohou zvýšit výkon."
  SETTING_BLOOM_QUALITY_TOOLTIP: "#T $SETTING_BLOOM_QUALITY$\n#!Povolí efekt rozjasnění, kde velmi jasná světla rozlévají světlo do dalších částí obrazu.\n\nNižší nastavení může zvýšit výkon."
  SETTING_FRAMERATE_CAP: "Maximální FPS"
  SETTING_FRAMERATE_CAP_TOOLTIP: "#T $SETTING_FRAMERATE_CAP$#!\nMaximální FPS, které hra vykreslí.\n\nNižší nastavení může snížit spotřebu energie."
  OPTION_CAP_30: "30"
  OPTION_CAP_60: "60"
  OPTION_CAP_90: "90"
  OPTION_CAP_120: "120"
  OPTION_CAP_144: "144"
  OPTION_CAP_165: "165"
