l_polish:
  SETTING_VALUE_WARNING: "$VALUE|0X$"
  SETTING_VALUE_PERCENTAGE_WARNING: "$VALUE|%0X$"
  RECOMMENDED_GUI_SCALE_TOO_HIGH: "#X Měřítko nad $VALUE|%0$ způsobí, že rozhraní budou přesahovat obrazovku#!"
  RECOMMENDED_GUI_SCALE: "Měřítko nad $VALUE|%0$ způsobí, že rozhraní budou přesahovat obrazovku"
