l_polish:
 SETTINGS_PAGE_GRAPHICS: "Grafika"
 SETTINGS_PAGE_GAME: "Hra"
 SETTINGS_PAGE_SYSTEM: "Systém"
 SETTINGS_PAGE_CONTROLS: "Ovládání"
 SETTINGS_PAGE_EDITOR: "Editor"
 SETTINGS_PAGE_INTERFACE: "Rozhraní"
 SETTINGS_PAGE_AUDIO: "Zvuk"
 SETTINGS_CATEGORY_SCREEN: "Obrazovka"
 SETTINGS_CATEGORY_QUALITY: "Kvalita"
 OPTION_EASY: "Lehká"
 OPTION_NORMAL: "Normální"
 OPTION_HARD: "Těžká"
 OPTION_NEVER: "Nikdy"
 OPTION_MONTHLY: "Každý měsíc"
 OPTION_HALFYEAR: "Každého půl roku"
 OPTION_YEARLY: "Každý rok"
 OPTION_FIVE_YEAR: "Každých pět let"
 OPTION_NO_AUTOSAVE: "Neukládat automaticky"
 SETTINGS_CATEGORY_ACCOUNT: "Účet"
 SETTINGS_CATEGORY_SYSTEM: "Systém"
 SETTINGS_CATEGORY_CONTROLS: "Ovládání"
 SETTINGS_CATEGORY_CAMERA: "Kamera"
 SETTINGS_CATEGORY_AUDIO: "Zvuk"
 SETTINGS_CATEGORY_GUI: "GUI"
 SETTINGS_CATEGORY_INPUT_BINDINGS: "Přiřazení kláves"
 DISCARD: "Zahodit"
 APPLY: "Použít"
 SAVE_AND_CLOSE: "OK"
 SETTINGS: "Nastavení"
 REQUIRES_RESTART: "Vyžaduje restart"
 REQUIRE_RESTART_DESCRIPTION: "Některá nastavení se projeví až po restartování hry."
 SETTINGS_INPUT_REMAP_INPUT: "Přiřadit vstup"
 SETTINGS_INPUT_CONFIRM: "Potvrdit"
 SETTINGS_INPUT_CANCEL: "Zrušit"
 SETTINGS_INPUT_CLEAR: "Vymazat"
 SETTINGS_INPUT_SAVE_INPUT_PROFILE: "Uložit profil"
 SETTINGS_INPUT_LOAD_INPUT_PROFILE: "Načíst profil"
 SETTINGS_INPUT_RESET_INPUT_PROFILE: "Obnovit výchozí"
 SETTINGS_INPUT_BINDING_TEXT: "Vyberte přiřazení vstupu pro akci '$INPUT_ACTION$':\n\n$INPUT_NAME$"
 SETTINGS_INPUT_BINDING_WARNING_TEXT: "Varování: Tento vstup je již přiřazen akci '$INPUT_ACTION$'!\nStisknutím '$SETTINGS_INPUT_CONFIRM$' staré přiřazení zrušíte."
 SETTINGS_INPUT_BINDING_MODIFIERS_WARNING_TEXT: "Varování: Přiřazení vstupu nemůže obsahovat pouze modifikační klávesy."
