l_polish:
 SETTING_INPUT_ACTION_BACK:0 "Zpět"
 SETTING_INPUT_ACTION_CAMERA_DOWN:0 "Posunout kameru dolů"
 SETTING_INPUT_ACTION_CAMERA_LEFT:0 "Posunout kameru doleva"
 SETTING_INPUT_ACTION_CAMERA_RIGHT:0 "Posunout kameru doprava"
 SETTING_INPUT_ACTION_CAMERA_UP:0 "Posunout kameru nahoru"
 SETTING_INPUT_ACTION_CONFIRM:0 "Potvrdit"
 SETTING_INPUT_ACTION_CONSTRUCTION_QUEUE:0 "Zpracování stavby"
 SETTING_INPUT_ACTION_CURRENT_SITUATION:0 "Aktuální situace"
 SETTING_INPUT_ACTION_DECREASE_SPEED:0 "Snížit rychlost"
 SETTING_INPUT_ACTION_DIPLOMATIC_LENS:0 "Diplomatická čočka"
 SETTING_INPUT_ACTION_GO_TO_DETAILS:0 "Přejít na detaily"
 SETTING_INPUT_ACTION_INCREASE_SPEED:0 "Zvýšit rychlost"
 SETTING_INPUT_ACTION_LOCATION_FINDER:0 "Hledání místa"
 SETTING_INPUT_ACTION_MAP_LIST:0 "Kniha"
 SETTING_INPUT_ACTION_MILITARY_LENS:0 "Armádní čočka"
 SETTING_INPUT_ACTION_NEXT_MUSIC_TRACK:0 "Další hudební skladba"
 SETTING_INPUT_ACTION_OPEN_BUDGET:0 "Rozpočet"
 SETTING_INPUT_ACTION_OPEN_BUILDINGS:0 "Budovy"
 SETTING_INPUT_ACTION_OPEN_COMPANIES: "Společnosti"
 SETTING_INPUT_ACTION_OPEN_DIPLOMATIC:0 "Diplomatický"
 SETTING_INPUT_ACTION_OPEN_JOURNAL:0 "Žurnál"
 SETTING_INPUT_ACTION_OPEN_MARKET:0 "Trh"
 SETTING_INPUT_ACTION_OPEN_MILITARY:0 "Armáda"
 SETTING_INPUT_ACTION_OPEN_OUTLINER:0 "Outliner"
 SETTING_INPUT_ACTION_OPEN_POLITICS:0 "Politika"
 SETTING_INPUT_ACTION_OPEN_POPULATION:0 "Populace"
 SETTING_INPUT_ACTION_OPEN_POWER_BLOC: "Silový blok"
 SETTING_INPUT_ACTION_OPEN_SOCIETY: "Společnost"
 SETTING_INPUT_ACTION_OPEN_TECHNOLOGY:0 "Technologie"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_ALL: "Zobrazit vše v Outlineru"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_DIPLOMACY: "Zobrazit diplomacii v Outlineru"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_ECONOMY: "Zobrazit ekonomiku v Outlineru"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_MILITARY: "Zobrazit armádu v Outlineru"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_PINNED: "Zobrazit připnuté v Outlineru"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_POLITICS: "Zobrazit politiku v Outlineru"
 SETTING_INPUT_ACTION_PAUSE:0 "Pauza / Obnovit"
 SETTING_INPUT_ACTION_PLAY_PAUSE_MUSIC:0 "Přehrát/Pozastavit hudbu"
 SETTING_INPUT_ACTION_POLITICAL_LENS:0 "Politická čočka"
 SETTING_INPUT_ACTION_PRODUCTION_LENS:0 "Producentní čočka"
 SETTING_INPUT_ACTION_SCROLL_DOWN:0 "Sjet dolů"
 SETTING_INPUT_ACTION_SCROLL_UP:0 "Sjet nahoru"
 SETTING_INPUT_ACTION_SPEED_FIVE:0 "Rychlost 5"
 SETTING_INPUT_ACTION_SPEED_FOUR:0 "Rychlost 4"
 SETTING_INPUT_ACTION_SPEED_ONE:0 "Rychlost 1"
 SETTING_INPUT_ACTION_SPEED_THREE:0 "Rychlost 3"
 SETTING_INPUT_ACTION_SPEED_TWO:0 "Rychlost 2"
 SETTING_INPUT_ACTION_TAB_1:0 "Karta 1"
 SETTING_INPUT_ACTION_TAB_2:0 "Karta 2"
 SETTING_INPUT_ACTION_TAB_3:0 "Karta 3"
 SETTING_INPUT_ACTION_TAB_4:0 "Karta 4"
 SETTING_INPUT_ACTION_TAB_5:0 "Karta 5"
 SETTING_INPUT_ACTION_TOGGLE_CONSTRUCTION_QUEUE_PAUSE:0 "Pauza/Obnovit zpracování stavby"
 SETTING_INPUT_ACTION_TOGGLE_GUI_DEBUG:0 "(Debug) gui.debug"
 SETTING_INPUT_ACTION_TOGGLE_PIN: "Přepnout připnutí"
 SETTING_INPUT_ACTION_TRADE_LENS:0 "Obchodní čočka"
 SETTING_INPUT_ACTION_ZOOM_TO: "Přiblížit"
 SETTING_INPUT_CONTEXT_COMMON:0 "Běžné"
 SETTING_INPUT_CONTEXT_COMMON_TOOLTIP:1 "Klávesové zkratky pro společný vstupní kontext"
