l_polish:
 SETTING_INPUT_CONTEXT_COMMON: "Běžné"
 SETTING_INPUT_CONTEXT_COMMON_TOOLTIP: "Klávesové zkratky pro společný vstupní kontext"
 SETTING_INPUT_ACTION_PAUSE: "Pauza / Obnovit"
 SETTING_INPUT_ACTION_INCREASE_SPEED: "Zvýšit rychlost"
 SETTING_INPUT_ACTION_DECREASE_SPEED: "Snížit rychlost"
 SETTING_INPUT_ACTION_SPEED_ONE: "Rychlost 1"
 SETTING_INPUT_ACTION_SPEED_TWO: "Rychlost 2"
 SETTING_INPUT_ACTION_SPEED_THREE: "Rychlost 3"
 SETTING_INPUT_ACTION_SPEED_FOUR: "Rychlost 4"
 SETTING_INPUT_ACTION_SPEED_FIVE: "Rychlost 5"
 SETTING_INPUT_ACTION_PLAY_PAUSE_MUSIC: "Přehrát/Pozastavit hudbu"
 SETTING_INPUT_ACTION_NEXT_MUSIC_TRACK: "Další hudební skladba"
 SETTING_INPUT_ACTION_CAMERA_UP: "Posunout kameru nahoru"
 SETTING_INPUT_ACTION_CAMERA_LEFT: "Posunout kameru doleva"
 SETTING_INPUT_ACTION_CAMERA_DOWN: "Posunout kameru dolů"
 SETTING_INPUT_ACTION_CAMERA_RIGHT: "Posunout kameru doprava"
 SETTING_INPUT_ACTION_LOCATION_FINDER: "Hledání místa"
 SETTING_INPUT_ACTION_OPEN_POLITICS: "Politika"
 SETTING_INPUT_ACTION_OPEN_BUDGET: "Rozpočet"
 SETTING_INPUT_ACTION_OPEN_BUILDINGS: "Budovy"
 SETTING_INPUT_ACTION_OPEN_MARKET: "Trh"
 SETTING_INPUT_ACTION_OPEN_MILITARY: "Armáda"
 SETTING_INPUT_ACTION_OPEN_DIPLOMATIC: "Diplomatický"
 SETTING_INPUT_ACTION_OPEN_TECHNOLOGY: "Technologie"
 SETTING_INPUT_ACTION_OPEN_SOCIETY: "Společnost"
 SETTING_INPUT_ACTION_OPEN_POPULATION: "Populace"
 SETTING_INPUT_ACTION_OPEN_JOURNAL: "Žurnál"
 SETTING_INPUT_ACTION_OPEN_POWER_BLOC: "Silový blok"
 SETTING_INPUT_ACTION_OPEN_COMPANIES: "Společnosti"
 SETTING_INPUT_ACTION_MAP_LIST: "Kniha"
 SETTING_INPUT_ACTION_BACK: "Zpět"
 SETTING_INPUT_ACTION_OPEN_OUTLINER: "Outliner"
 SETTING_INPUT_ACTION_TAB_1: "Karta 1"
 SETTING_INPUT_ACTION_TAB_2: "Karta 2"
 SETTING_INPUT_ACTION_TAB_3: "Karta 3"
 SETTING_INPUT_ACTION_TAB_4: "Karta 4"
 SETTING_INPUT_ACTION_TAB_5: "Karta 5"
 SETTING_INPUT_ACTION_PRODUCTION_LENS: "Stavební čočka"
 SETTING_INPUT_ACTION_POLITICAL_LENS: "Politická čočka"
 SETTING_INPUT_ACTION_DIPLOMATIC_LENS: "Diplomatická čočka"
 SETTING_INPUT_ACTION_MILITARY_LENS: "Armádní čočka"
 SETTING_INPUT_ACTION_TRADE_LENS: "Obchodní čočka"
 SETTING_INPUT_ACTION_CONFIRM: "Potvrdit"
 SETTING_INPUT_ACTION_CURRENT_SITUATION: "Aktuální situace"
 SETTING_INPUT_ACTION_CONSTRUCTION_QUEUE: "Zpracování stavby"
 SETTING_INPUT_ACTION_TOGGLE_CONSTRUCTION_QUEUE_PAUSE: "Pauza/Obnovit zpracování stavby"
 SETTING_INPUT_ACTION_GO_TO_DETAILS: "Přejít na detaily"
 SETTING_INPUT_ACTION_SCROLL_UP: "Sjet nahoru"
 SETTING_INPUT_ACTION_SCROLL_DOWN: "Sjet dolů"
 SETTING_INPUT_ACTION_TOGGLE_GUI_DEBUG: "(Debug) gui.debug"
 SETTING_INPUT_ACTION_DISMISS_TOAST: "Zavřít oznámení" # todo: NEW TRANSLATION
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_PINNED: "Zobrazit připnuté v Outlineru"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_ECONOMY: "Zobrazit ekonomiku v Outlineru"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_POLITICS: "Zobrazit politiku v Outlineru"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_DIPLOMACY: "Zobrazit diplomacii v Outlineru"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_MILITARY: "Zobrazit armádu v Outlineru"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_ALL: "Zobrazit vše v Outlineru"
 SETTING_INPUT_ACTION_TOGGLE_PIN: "Přepnout připnutí"
 SETTING_INPUT_ACTION_ZOOM_TO: "Přiblížit"
 SETTING_INPUT_ACTION_MERGE: "Spojit"
 SETTING_INPUT_ACTION_COUNTRY_PANEL: "Detaily země"
