l_polish:
 pm_ammonia-soda_process: "Proces ammoniak-soda"
 pm_apple_orchards: "Jablečné sady"
 pm_artificial_fertilizers: "Umělá hnojiva"
 pm_artillery_production: "Výroba děl"
 pm_automatic_power_looms: "Automatické tkalcovské stavy"
 pm_automobile_production: "Výroba automobilů"
 pm_brine_electrolysis: "Elektrolýza solanky"
 pm_citrus_orchards: "Citrusové sady"
 pm_civilian_priority: "Civilní priorita"
 pm_craftsman_sewing: "Precizní výroba"
 pm_dyes_production: "Výroba barviv"
 pm_electric_sewing_machines: "Elektrické šicí stroje"
 pm_fig_orchards: "Fíkové sady"
 pm_fig_orchards_building_rice_farm: "Fíkové sady"
 pm_improved_fertilizer: "Zlepšená hnojiva"
 pm_leaded_glass: "Sklo s olovem"
 pm_leblanc_process: "Leblancův proces"
 pm_manual_glassblowing: "Ruční sklenářství"
 pm_mechanized_looms: "Mechanizované tkalcovské stavy"
 pm_military_priority: "Vojenská priorita"
 pm_mulberry_groves: "Morušové háje"
 pm_nitrogen_fixation: "Proces fixace dusíku"
 pm_no_artificial_fertilizers: "Žádná umělá hnojiva"
 pm_no_artificial_fibers: "Prioritizovat výrobu barviv"
 pm_no_artillery_production: "Prioritizovat výrobu malých zbraní"
 pm_no_explosives_production: "Prioritizovat výrobu hnojiv"
 pm_no_secondary: "Udržovat jednu plodinu"
 pm_no_synthetic_dyes: "Žádné syntetické barviva"
 pm_potatoes: "Brambory"
 pm_primary: "Primární"
 pm_rayon: "Viskóza"
 pm_sewing_machines: "Šicí stroje"
 pm_silk_production: "Výroba hedvábí"
 pm_steamworks: "Parní dílna"
 pm_traditional_looms: "Tradiční tkalcovské stavy"
 pm_vacuum_evaporation: "Vakuová evaporace"
 pm_vineyards: "Vinice"
 pm_vineyards_building_maize_farm: "Vinice"
 pmg_automation: "Automatizace"
 pmg_automation_building_food_industry: "Automatizace"
 pmg_automation_building_motor_industry: "Automatizace"
 pmg_automobile_production: "Výroba automobilů"
 pmg_fertilizer_production: "Výroba hnojiv"
 pmg_secondary_building_maize_farm: "Sekundární"
 pmg_secondary_building_millet_farm: "Sekundární"
 pmg_secondary_building_rice_farm: "Sekundární"
 pmg_secondary_building_rye_farm: "Sekundární"
 pmg_secondary_building_wheat_farm: "Sekundární"
 pmg_synthetic_dyes: "Syntetická barviva"
 pmg_automation_building_automotive_industry: "$pmg_automation$"
 pm_mass_automobile_production: "Výroba ve velkém"
 pm_sugar_beets: "Cukrová řepa"
 pmg_automation_building_textile_mill: "Automatizace" # todo: NEW TRANSLATION
 pmg_automation_building_furniture_manufactory: "Automatizace" # todo: NEW TRANSLATION
 pmg_automation_building_tooling_workshop: "Automatizace" # todo: NEW TRANSLATION
 pmg_automation_building_paper_mill: "Automatizace" # todo: NEW TRANSLATION
 pmg_automation_building_steel_mill: "Automatizace" # todo: NEW TRANSLATION
