l_polish:
 pm_ammonia-soda_process:0 "Proces ammoniak-soda"
 pm_apple_orchards:0 "Jablečné sady"
 pm_artificial_fertilizers:0 "Umělá hnojiva"
 pm_artillery_production:0 "Výroba děl"
 pm_automatic_power_looms:0 "Automatické tkalcovské stavy"
 pm_automobile_production:0 "Výroba automobilů"
 pm_brine_electrolysis:0 "Elektrolýza solanky"
 pm_citrus_orchards:0 "Citrusové sady"
 pm_civilian_priority:0 "Civilní priorita"
 pm_craftsman_sewing:0 "Precizní výroba"
 pm_dyes_production:0 "Výroba barviv"
 pm_electric_sewing_machines:0 "Elektrické šicí stroje"
 pm_fig_orchards:0 "Fíkové sady"
 pm_fig_orchards_building_rice_farm:0 "Fíkové sady"
 pm_improved_fertilizer:0 "Zlepšená hnojiva"
 pm_leaded_glass:0 "Sklo s olovem"
 pm_leblanc_process:0 "Leblancův proces"
 pm_manual_glassblowing:0 "Ruční sklenářství"
 pm_mechanized_looms:0 "Mechanizované tkalcovské stavy"
 pm_military_priority:0 "Vojenská priorita"
 pm_mulberry_groves:0 "Morušové háje"
 pm_nitrogen_fixation:0 "Proces fixace dusíku"
 pm_no_artificial_fertilizers:0 "Žádná umělá hnojiva"
 pm_no_artificial_fibers:0 "Prioritizovat výrobu barviv"
 pm_no_artillery_production:0 "Prioritizovat výrobu malých zbraní"
 pm_no_explosives_production:0 "Prioritizovat výrobu hnojiv"
 pm_no_secondary:0 "Udržovat jednu plodinu"
 pm_no_synthetic_dyes:0 "Žádné syntetické barviva"
 pm_potatoes:0 "Brambory"
 pm_primary:0 "Primární"
 pm_rayon:0 "Viskóza"
 pm_sewing_machines:0 "Šicí stroje"
 pm_silk_production:0 "Výroba hedvábí"
 pm_steamworks:0 "Parní dílna"
 pm_traditional_looms:0 "Tradiční tkalcovské stavy"
 pm_vacuum_evaporation:0 "Vakuová evaporace"
 pm_vineyards:0 "Vinice"
 pm_vineyards_building_maize_farm:0 "Vinice"
 pmg_automation:0 "Automatizace"
 pmg_automation_building_food_industry:0 "Automatizace"
 pmg_automation_building_furniture_manufacturies:0 "Automatizace"
 pmg_automation_building_motor_industry:0 "Automatizace"
 pmg_automation_building_paper_mills:0 "Automatizace"
 pmg_automation_building_steel_mills:0 "Automatizace"
 pmg_automation_building_textile_mills:0 "Automatizace"
 pmg_automation_building_tooling_workshops:0 "Automatizace"
 pmg_automobile_production:0 "Výroba automobilů"
 pmg_fertilizer_production:0 "Výroba hnojiv"
 pmg_secondary_building_maize_farm:0 "Sekundární"
 pmg_secondary_building_millet_farm:0 "Sekundární"
 pmg_secondary_building_rice_farm:0 "Sekundární"
 pmg_secondary_building_rye_farm:0 "Sekundární"
 pmg_secondary_building_wheat_farm:0 "Sekundární"
 pmg_synthetic_dyes:0 "Syntetická barviva"
 pmg_automation_building_automotive_industry: "$pmg_automation$"
 pm_mass_automobile_production: "Výroba ve velkém"
