l_polish:
 SETTING_REFRACTION: "Refrakce"
 SETTING_REFRACTION_QUALITY: "Kvalita refrakce"
 SETTING_MAPOBJECT_QUALITY: "Kvalita mapových objektů"
 SETTING_MAP_SSAO: "Mapové SSAO"
 SETTING_DOF: "Hluboké ostření"
 SETTING_LENS_FLARE: "Odlesk objektivu"
 SETTING_SECONDARY_LENS_FLARE: "Sekundární odlesk objektivu"
